name: Build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'metadata/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dumdum:
    name: build
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2023.09-ndk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Build
        env:
          ALIAS_NAME: dumdum
          ALIAS_PASS: "${{ secrets.JKS_PASS }}"
          KEYSTORE_PASS: "${{ secrets.JKS_PASS }}"
        run: |
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
          echo "ndk.dir=${ANDROID_NDK_ROOT}" >> local.properties
          echo "${{ secrets.JKS_B64 }}" | base64 --decode >> dumdum.jks
          ./gradlew app:assembleGitHubRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "DumDum-${{ github.run_number }}"
          path: app/build/outputs/apk/github/release/*.apk
