name: Build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'metadata/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.24.2

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2023.09-ndk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./libcore/go.sum

      - name: Build libcore
        run: bash -x ./libcore/scripts/build.sh

      - name: Build DumDum
        env:
          ALIAS_NAME: dumdum
          ALIAS_PASS: "${{ secrets.JKS_PASS }}"
          KEYSTORE_PASS: "${{ secrets.JKS_PASS }}"
        run: |
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
          echo "ndk.dir=${ANDROID_NDK_ROOT}" >> local.properties
          echo "${{ secrets.JKS_B64 }}" | base64 --decode >> dumdum.jks
          mkdir -v ./app/libs
          mv -v ./libcore/libcore.aar ./app/libs/libcore.aar
          ./gradlew app:assembleGitHubRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "DumDum-${{ github.run_number }}"
          path: ./app/build/outputs/apk/github/release/*.apk
